#include <string>
#include <string.h>
#include <stdint.h>
#include "openssl/md5.h"  
#include "openssl/sha.h" 
#include "openssl/hmac.h"
#include "openssl/evp.h"
#include <iomanip>
#include <map>
#include <math.h>
#include <sstream>
#include <boost/random.hpp>
#include <boost/random/random_device.hpp>
#include <thread>
#include <numeric>
#include <fstream>
#include <stdio.h>
#include <inttypes.h>
#include <string.h>
#include <bitset>
#include <unordered_map>
#include <set>
#include <tuple>
#include <openssl/rand.h>